name: Contexts
on: push
jobs:
  context:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }}
    steps:
      - run: echo "${ACTOR} is running this workflow on the ${GITHUB_REF} branch of the ${GITHUB_REPOSITORY} repository."