name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: 'A cheerful word'
        required: true
        default: 'Hello'
jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.greeting }}, world!"
      - uses: actions/setup-go@v7
        with:
          go-version: '1.24'